### Вычисления с помощью Numpy

### Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [10]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [11]:
a_centered_sp / (a_centered.shape[0] - 1)


2.0

### Задание 4

In [12]:
np.cov(a.T)[0, 1]

2.0

### Работа с данными в Pandas

### Задание 1

In [2]:
import pandas as pd

In [3]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                       columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [4]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[350, 200, 450, 500, 350, 320, 290]}, 
                    columns=['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    350
1          1                 Рудин    200
2          1     Дворянское гнездо    450
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    350
5          3                 Гроза    320
6          3  Таланты и поклонники    290

### Задание 2

In [7]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    350
1          1    Тургенев                 Рудин    200
2          1    Тургенев     Дворянское гнездо    450
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    350
5          3  Островский                 Гроза    320
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [8]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
2          1    Тургенев  Дворянское гнездо    450
0          1    Тургенев        Отцы и дети    350
4          2       Чехов    Дама с собачкой    350
5          3  Островский              Гроза    320

In [17]:
top5.reset_index(inplace = True, drop=True)
top5

level_0  index author_name         book_title  price
0        0      3       Чехов   Толстый и тонкий    500
1        1      2    Тургенев  Дворянское гнездо    450
2        2      0    Тургенев        Отцы и дети    350
3        3      4       Чехов    Дама с собачкой    350
4        4      5  Островский              Гроза    320

### Задание 4

In [21]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       320  305.000000
Тургенев          200       450  333.333333
Чехов             350       500  425.000000

### Задание 5

In [22]:
import numpy as np

In [23]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    350  твердая
1          1    Тургенев                 Рудин    200   мягкая
2          1    Тургенев     Дворянское гнездо    450   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    350  твердая
5          3  Островский                 Гроза    320   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [24]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    610.0      0.0
Тургенев      650.0    350.0
Чехов           0.0    850.0

In [25]:
book_info.to_pickle('book_info.pkl')

In [26]:
book_info2 = pd.read_pickle('book_info.pkl')

In [27]:
book_info.equals(book_info2)

True